version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: epitodo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epytodo
      MYSQL_USER: user
      MYSQL_PASSWORD: "0123456789"
    ports:
      - "3036:3036"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Si tu veux initialiser la DB

volumes:
  mysql_data:
